version: "3.9"

services:
  extractor:
    build:
      context: ./extractor-service
      dockerfile: ../Dockerfile
    container_name: extractor-service
    restart: always
    env_file:
      - .env
    volumes:
      - ./extractor-service/app:/app
    depends_on:
      - kafka
    networks:
      - f1-network






  stream-processor:
    build:
      context: ./stream-processor-service
      dockerfile: Dockerfile
    container_name: stream-processor-service
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      kafka: 
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - f1-network




  redis:
    image: redis:7.2.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly no
    networks:
      - f1-network



  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    hostname: kafka

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      # ---------- KRaft ----------
      KAFKA_KRAFT_MODE: true
      CLUSTER_ID: KfPjRNKiSCqHZDTPO9UDaw
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # ---------- Listeners ----------
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # ---------- Storage ----------
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - kafka_kraft:/var/lib/kafka/data
    networks:
      - f1-network


volumes:
  kafka_kraft:

networks:
  f1-network:
    driver: bridge
